// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6C6ejouoYexEYbYlbaHk4NcnJVt4FzUo',
    appId: '1:788754672140:web:6e1b3ebd37542be1509c29',
    messagingSenderId: '788754672140',
    projectId: 'love-the-world-001',
    authDomain: 'love-the-world-001.firebaseapp.com',
    storageBucket: 'love-the-world-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjH2YVkU9TSpjBMiQQYAwXd6rekyFA5RU',
    appId: '1:788754672140:ios:f5853ab09310b783509c29',
    messagingSenderId: '788754672140',
    projectId: 'love-the-world-001',
    storageBucket: 'love-the-world-001.firebasestorage.app',
    iosBundleId: 'com.example.loveTheWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjH2YVkU9TSpjBMiQQYAwXd6rekyFA5RU',
    appId: '1:788754672140:ios:f5853ab09310b783509c29',
    messagingSenderId: '788754672140',
    projectId: 'love-the-world-001',
    storageBucket: 'love-the-world-001.firebasestorage.app',
    iosBundleId: 'com.example.loveTheWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6C6ejouoYexEYbYlbaHk4NcnJVt4FzUo',
    appId: '1:788754672140:web:1a46533a74be1d88509c29',
    messagingSenderId: '788754672140',
    projectId: 'love-the-world-001',
    authDomain: 'love-the-world-001.firebaseapp.com',
    storageBucket: 'love-the-world-001.firebasestorage.app',
  );

}